### ISSUE TITLE
Build fails on macOS: `socket.cpp:1 error: use of undeclared identifier 'MSG_NOSIGNAL'`; `x11.hpp: error: no member named 'jthread' in namespace 'std'`

### ISSUE THREAD

**Issue by barracuda156** [jstkdng/ueberzugpp#280]
On macOS 10.15.8 with clang 17.0.6:

```
:info:build [ 56%] Building CXX object CMakeFiles/ueberzug.dir/src/util/socket.cpp.o
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/util/socket.cpp.o -MF CMakeFiles/ueberzug.dir/src/util/socket.cpp.o.d -o CMakeFiles/ueberzug.dir/src/util/socket.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/util/socket.cpp
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/flags.cpp.o -MF CMakeFiles/ueberzug.dir/src/flags.cpp.o.d -o CMakeFiles/ueberzug.dir/src/flags.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/flags.cpp
:info:build [ 60%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas.cpp.o
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/canvas.cpp.o -MF CMakeFiles/ueberzug.dir/src/canvas.cpp.o.d -o CMakeFiles/ueberzug.dir/src/canvas.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas.cpp
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/dimensions.cpp.o -MF CMakeFiles/ueberzug.dir/src/dimensions.cpp.o.d -o CMakeFiles/ueberzug.dir/src/dimensions.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/dimensions.cpp
:info:build [ 65%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/chafa.cpp.o
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/canvas/chafa.cpp.o -MF CMakeFiles/ueberzug.dir/src/canvas/chafa.cpp.o.d -o CMakeFiles/ueberzug.dir/src/canvas/chafa.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/chafa.cpp
:info:build [ 69%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/sixel.cpp.o
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/canvas/sixel.cpp.o -MF CMakeFiles/ueberzug.dir/src/canvas/sixel.cpp.o.d -o CMakeFiles/ueberzug.dir/src/canvas/sixel.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/sixel.cpp
:info:build [ 73%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/kitty/kitty.cpp.o
:info:build [ 78%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/kitty/chunk.cpp.o
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/canvas/kitty/chunk.cpp.o -MF CMakeFiles/ueberzug.dir/src/canvas/kitty/chunk.cpp.o.d -o CMakeFiles/ueberzug.dir/src/canvas/kitty/chunk.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/kitty/chunk.cpp
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/canvas/kitty/kitty.cpp.o -MF CMakeFiles/ueberzug.dir/src/canvas/kitty/kitty.cpp.o.d -o CMakeFiles/ueberzug.dir/src/canvas/kitty/kitty.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/kitty/kitty.cpp
:info:build [ 82%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/iterm2/iterm2.cpp.o
:info:build /opt/local/bin/ccache /opt/local/bin/clang++-mp-17 -DENABLE_X11 -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/include -I/opt/local/var/macports/build/ueberzugpp-820f3467/work/build -isystem /opt/local/include -isystem /opt/local/include/libfmt11 -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/libexec/onetbb/include -isystem /opt/local/include/webp -isystem /opt/local/include/pango-1.0 -isystem /opt/local/include/harfbuzz -isystem /opt/local/include/fribidi -isystem /opt/local/include/librsvg-2.0 -isystem /opt/local/include/gdk-pixbuf-2.0 -isystem /opt/local/include/cairo -isystem /opt/local/include/pixman-1 -isystem /opt/local/include/freetype2 -isystem /opt/local/include/libpng16 -isystem /opt/local/include/OpenEXR -isystem /opt/local/include/Imath -isystem /opt/local/include/libraw -isystem /opt/local/include/openjpeg-2.5 -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/include/chafa -isystem /opt/local/lib/chafa/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=c++20 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -pthread -D_FILE_OFFSET_BITS=64 -DHWY_SHARED_DEFINE -MD -MT CMakeFiles/ueberzug.dir/src/canvas/iterm2/iterm2.cpp.o -MF CMakeFiles/ueberzug.dir/src/canvas/iterm2/iterm2.cpp.o.d -o CMakeFiles/ueberzug.dir/src/canvas/iterm2/iterm2.cpp.o -c /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/iterm2/iterm2.cpp
:info:build /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/util/socket.cpp:122:51: error: use of undeclared identifier 'MSG_NOSIGNAL'
:info:build   122 |         const auto status = send(fd, runner, len, MSG_NOSIGNAL);
:info:build       |                                                   ^
:info:build 1 error generated.
:info:build make[2]: *** [CMakeFiles/ueberzug.dir/src/util/socket.cpp.o] Error 1
:info:build make[2]: *** Waiting for unfinished jobs....
:info:build In file included from /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas.cpp:23:
:info:build /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/x11/x11.hpp:74:42: error: no member named 'jthread' in namespace 'std'
:info:build    74 |     std::unordered_map<std::string, std::jthread> draw_threads;
:info:build       |                                     ~~~~~^
:info:build /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas.cpp:45:16: error: no viable conversion from returned value of type 'unique_ptr<X11Canvas>' to function return type 'unique_ptr<Canvas>'
:info:build    45 |         return std::make_unique<X11Canvas>();
:info:build       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build /opt/local/libexec/llvm-17/bin/../include/c++/v1/__memory/unique_ptr.h:127:59: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'typename __unique_if<X11Canvas>::__unique_single' (aka 'unique_ptr<X11Canvas>') to 'const unique_ptr<Canvas> &' for 1st argument
:info:build   127 | class _LIBCPP_UNIQUE_PTR_TRIVIAL_ABI _LIBCPP_TEMPLATE_VIS unique_ptr {
:info:build       |                                                           ^~~~~~~~~~
:info:build /opt/local/libexec/llvm-17/bin/../include/c++/v1/__memory/unique_ptr.h:191:21: note: candidate constructor template not viable: no known conversion from 'typename __unique_if<X11Canvas>::__unique_single' (aka 'unique_ptr<X11Canvas>') to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
:info:build   191 |   _LIBCPP_CONSTEXPR unique_ptr(nullptr_t) _NOEXCEPT : __ptr_(__value_init_tag(), __value_init_tag()) {}
:info:build       |                     ^          ~~~~~~~~~
:info:build /opt/local/libexec/llvm-17/bin/../include/c++/v1/__memory/unique_ptr.h:213:59: note: candidate constructor not viable: no known conversion from 'typename __unique_if<X11Canvas>::__unique_single' (aka 'unique_ptr<X11Canvas>') to 'unique_ptr<Canvas> &&' for 1st argument
:info:build   213 |   _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 unique_ptr(unique_ptr&& __u) _NOEXCEPT
:info:build       |                                                           ^          ~~~~~~~~~~~~~~~~
:info:build /opt/local/libexec/llvm-17/bin/../include/c++/v1/__memory/unique_ptr.h:220:59: note: candidate template ignored: requirement 'is_convertible<X11Canvas *, Canvas *>::value' was not satisfied [with _Up = X11Canvas, _Ep = std::default_delete<X11Canvas>]
:info:build   220 |   _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 unique_ptr(unique_ptr<_Up, _Ep>&& __u) _NOEXCEPT
:info:build       |                                                           ^
:info:build /opt/local/libexec/llvm-17/bin/../include/c++/v1/__memory/unique_ptr.h:194:68: note: explicit constructor is not a candidate
:info:build   194 |   _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 explicit unique_ptr(pointer __p) _NOEXCEPT
:info:build       |                                                                    ^
:info:build 2 errors generated.
:info:build make[2]: *** [CMakeFiles/ueberzug.dir/src/canvas.cpp.o] Error 1
:info:build In file included from /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/x11/x11.cpp:17:
:info:build /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/x11/x11.hpp:74:42: error: no member named 'jthread' in namespace 'std'
:info:build    74 |     std::unordered_map<std::string, std::jthread> draw_threads;
:info:build       |                                     ~~~~~^
:info:build /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/x11/x11.cpp:92:90: error: no type named 'stop_token' in namespace 'std'
:info:build    92 |     draw_threads.insert_or_assign(identifier, std::jthread([this, identifier](const std::stop_token &stoken) {
:info:build       |                                                                                     ~~~~~^
:info:build /opt/local/var/macports/build/ueberzugpp-820f3467/work/ueberzugpp-2.9.8/src/canvas/x11/x11.cpp:92:52: error: no member named 'jthread' in namespace 'std'
:info:build    92 |     draw_threads.insert_or_assign(identifier, std::jthread([this, identifier](const std::stop_token &stoken) {
:info:build       |                                               ~~~~~^
:info:build 3 errors generated.
```

**Comment by barracuda156** [comment]
Fixes this and another error: https://github.com/jstkdng/ueberzugpp/pull/281

**Comment by jstkdng** [comment]
wow, that is an old version of Macos, what is the other error?

**Comment by barracuda156** [comment]
@jstkdng The second issue is that this cannot compile on < 10.7: https://github.com/jstkdng/ueberzugpp/blob/c1c76e34bac97403ed3f2f403fcf96b5cfd0b914/src/process/apple.cpp#L32-L35

10.6 SDK header: https://github.com/alexey-lysiuk/macos-sdk/blob/98075949035403f5707514e6c2d4933292568f9e/MacOSX10.6.sdk/usr/include/sys/proc_info.h#L564-L602
10.7 SDK header: https://github.com/alexey-lysiuk/macos-sdk/blob/98075949035403f5707514e6c2d4933292568f9e/MacOSX10.7.sdk/usr/include/sys/proc_info.h#L596-L640

I used a fallback similar to what `tmux` has. Or if `PROC_PIDTBSDINFO` is sufficient, then that is present in 10.6.

**Comment by jstkdng** [comment]
Merged on 2.9.9
