### ISSUE TITLE
compilation errror: `spdlog` multiple definitions

### ISSUE THREAD

**Issue by danjenson** [jstkdng/ueberzugpp#116]
Full log:
```
$ git clone https://github.com/jstkdng/ueberzugpp.git
cd ueberzugpp
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
Cloning into 'ueberzugpp'...
remote: Enumerating objects: 4091, done.
remote: Counting objects: 100% (1417/1417), done.
remote: Compressing objects: 100% (414/414), done.
remote: Total 4091 (delta 1130), reused 1233 (delta 999), pack-reused 2674
Receiving objects: 100% (4091/4091), 1.17 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (2961/2961), done.
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1t")
-- Looking for std::execution::par_unseq
-- Looking for std::execution::par_unseq - found
-- Using the multi-header code from /data/scratch/ueberzugpp/build/_deps/nlohmann_json-src/include/
-- Build spdlog: 1.12.0
-- Build type: Release
-- Checking for module 'xcb'
--   Found xcb, version 1.15
-- Checking for module 'xcb-image'
--   Found xcb-image, version 0.4.1
-- Checking for module 'xcb-res'
--   Found xcb-res, version 1.15
-- Found OpenCV: /usr (found version "4.6.0") found components: core imgproc imgcodecs videoio
-- Checking for module 'vips-cpp'
--   Found vips-cpp, version 8.14.2
-- Checking for module 'libsixel'
--   Found libsixel, version 1.10.3
-- Checking for module 'chafa>=1.6'
--   Found chafa, version 1.12.5
-- Configuring done (5.4s)
-- Generating done (0.0s)
-- Build files have been written to: /data/scratch/ueberzugpp/build
[  3%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/spdlog.cpp.o
[  6%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
[  9%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
[ 12%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
[ 15%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o
[ 18%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/cfg.cpp.o
[ 21%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/bundled_fmtlib_format.cpp.o
[ 25%] Linking CXX static library libspdlog.a
[ 25%] Built target spdlog
[ 25%] Built target CLI11
[ 28%] Building CXX object CMakeFiles/ueberzug.dir/src/util/x11.cpp.o
[ 31%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/x11/x11.cpp.o
[ 34%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/x11/window/x11.cpp.o
[ 37%] Building CXX object CMakeFiles/ueberzug.dir/src/image/opencv.cpp.o
[ 40%] Building CXX object CMakeFiles/ueberzug.dir/src/process/linux.cpp.o
[ 43%] Building CXX object CMakeFiles/ueberzug.dir/src/main.cpp.o
[ 46%] Building CXX object CMakeFiles/ueberzug.dir/src/application.cpp.o
[ 50%] Building CXX object CMakeFiles/ueberzug.dir/src/os.cpp.o
[ 53%] Building CXX object CMakeFiles/ueberzug.dir/src/tmux.cpp.o
[ 56%] Building CXX object CMakeFiles/ueberzug.dir/src/terminal.cpp.o
[ 59%] Building CXX object CMakeFiles/ueberzug.dir/src/dimensions.cpp.o
[ 62%] Building CXX object CMakeFiles/ueberzug.dir/src/flags.cpp.o
[ 65%] Building CXX object CMakeFiles/ueberzug.dir/src/util/util.cpp.o
[ 68%] Building CXX object CMakeFiles/ueberzug.dir/src/util/socket.cpp.o
[ 71%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas.cpp.o
[ 75%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/chafa.cpp.o
[ 78%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/sixel.cpp.o
[ 81%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/kitty/kitty.cpp.o
In file included from /usr/include/c++/12.2/pstl/parallel_backend_tbb.h:26,
                 from /usr/include/c++/12.2/pstl/parallel_backend.h:20,
                 from /usr/include/c++/12.2/pstl/algorithm_impl.h:22,
                 from /usr/include/c++/12.2/pstl/glue_execution_defs.h:50,
                 from /usr/include/c++/12.2/execution:32,
                 from /data/scratch/ueberzugpp/src/canvas/kitty/kitty.cpp:28:
/usr/include/tbb/task.h:21:139: note: '#pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.'
   21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                                                                                           ^
[ 84%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/kitty/chunk.cpp.o
[ 87%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/iterm2/iterm2.cpp.o
In file included from /usr/include/c++/12.2/pstl/parallel_backend_tbb.h:26,
                 from /usr/include/c++/12.2/pstl/parallel_backend.h:20,
                 from /usr/include/c++/12.2/pstl/algorithm_impl.h:22,
                 from /usr/include/c++/12.2/pstl/glue_execution_defs.h:50,
                 from /usr/include/c++/12.2/execution:32,
                 from /data/scratch/ueberzugpp/src/canvas/iterm2/iterm2.cpp:33:
/usr/include/tbb/task.h:21:139: note: '#pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.'
   21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                                                                                           ^
[ 90%] Building CXX object CMakeFiles/ueberzug.dir/src/canvas/iterm2/chunk.cpp.o
[ 93%] Building CXX object CMakeFiles/ueberzug.dir/src/image.cpp.o
[ 96%] Building CXX object CMakeFiles/ueberzug.dir/src/image/libvips.cpp.o
[100%] Linking CXX executable ueberzug
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
spdlog.cpp:(.text+0x9900): multiple definition of `spdlog::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x10a0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::set_formatter(std::unique_ptr<spdlog::formatter, std::default_delete<spdlog::formatter> >)':
spdlog.cpp:(.text+0x99a0): multiple definition of `spdlog::set_formatter(std::unique_ptr<spdlog::formatter, std::default_delete<spdlog::formatter> >)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x10f0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::enable_backtrace(unsigned long)':
spdlog.cpp:(.text+0x9a30): multiple definition of `spdlog::enable_backtrace(unsigned long)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1160): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::disable_backtrace()':
spdlog.cpp:(.text+0x9aa0): multiple definition of `spdlog::disable_backtrace()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1180): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::set_level(spdlog::level::level_enum)':
spdlog.cpp:(.text+0x9b30): multiple definition of `spdlog::set_level(spdlog::level::level_enum)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1200): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::flush_on(spdlog::level::level_enum)':
spdlog.cpp:(.text+0x9b90): multiple definition of `spdlog::flush_on(spdlog::level::level_enum)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1220): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::set_error_handler(void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))':
spdlog.cpp:(.text+0x9bf0): multiple definition of `spdlog::set_error_handler(void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1240): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::apply_all(std::function<void (std::shared_ptr<spdlog::logger>)> const&)':
spdlog.cpp:(.text+0x9ca0): multiple definition of `spdlog::apply_all(std::function<void (std::shared_ptr<spdlog::logger>)> const&)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x12f0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::drop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
spdlog.cpp:(.text+0x9cc0): multiple definition of `spdlog::drop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1310): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::drop_all()':
spdlog.cpp:(.text+0x9d60): multiple definition of `spdlog::drop_all()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1330): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::shutdown()':
spdlog.cpp:(.text+0x9d80): multiple definition of `spdlog::shutdown()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1350): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::set_automatic_registration(bool)':
spdlog.cpp:(.text+0x9ea0): multiple definition of `spdlog::set_automatic_registration(bool)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1370): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::default_logger()':
spdlog.cpp:(.text+0x9ee0): multiple definition of `spdlog::default_logger()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1390): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::default_logger_raw()':
spdlog.cpp:(.text+0x9f50): multiple definition of `spdlog::default_logger_raw()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x13e0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::dump_backtrace()':
spdlog.cpp:(.text+0x9f70): multiple definition of `spdlog::dump_backtrace()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x11a0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::get_level()':
spdlog.cpp:(.text+0x9f90): multiple definition of `spdlog::get_level()'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x11c0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::should_log(spdlog::level::level_enum)':
spdlog.cpp:(.text+0x9fb0): multiple definition of `spdlog::should_log(spdlog::level::level_enum)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x11e0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::apply_logger_env_levels(std::shared_ptr<spdlog::logger>)':
spdlog.cpp:(.text+0x9fd0): multiple definition of `spdlog::apply_logger_env_levels(std::shared_ptr<spdlog::logger>)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1550): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::set_pattern(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, spdlog::pattern_time_type)':
spdlog.cpp:(.text+0xa070): multiple definition of `spdlog::set_pattern(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, spdlog::pattern_time_type)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x42a0): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::initialize_logger(std::shared_ptr<spdlog::logger>)':
spdlog.cpp:(.text+0xa800): multiple definition of `spdlog::initialize_logger(std::shared_ptr<spdlog::logger>)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1400): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::register_logger(std::shared_ptr<spdlog::logger>)':
spdlog.cpp:(.text+0xa900): multiple definition of `spdlog::register_logger(std::shared_ptr<spdlog::logger>)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x1470): first defined here
/usr/bin/ld: _deps/spdlog-build/libspdlog.a(spdlog.cpp.o): in function `spdlog::set_default_logger(std::shared_ptr<spdlog::logger>)':
spdlog.cpp:(.text+0xa9a0): multiple definition of `spdlog::set_default_logger(std::shared_ptr<spdlog::logger>)'; CMakeFiles/ueberzug.dir/src/main.cpp.o:main.cpp:(.text+0x14e0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ueberzug.dir/build.make:468: ueberzug] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/ueberzug.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by danjenson** [comment]
Worked with `spdlog` 1.11

**Comment by jstkdng** [comment]
should be working now with 1.12
